language: node_js
node_js:
- '0.12'
env:
  global:
    secure: uhGr2vWqpM2a97Wg4f7SfEv0O3sjr5LZESq42WsHwWuLJnie0HdvyhOJk1PqHbLKrS7TNmJQIQJ54QBTRA4JUQeLog7liXCfSSbzV66VWLF5qH1gnfGOi67BSWee56iUn1yuwlgmPHmfXVdoA4vMINJ/ejZ06UvSiI07bn5QTFF3TCqexT0U81LCgRfloDjk6LKyb/VSpAUi1DY3MlXlpa4ez22bGoiIWoZfTV8gbkR36qnlPTqE5kNT09794nYlpeX35KNKHdWtdnU9VWVjZE6K6t+ZWBJhaDc3CMLT/wxz/69q66Aqku/2wjRkrWMsJ+n2+NwHU2l/IJR5qEQ7nVUlJ0BMPE/vNxAtB/Ss4WivddwZV0hwcOI10en38GwXmFeLCvsa8LEwxNpg2DWj7fltdqkFDhzWV5cvwxOt6bb4odq1Ziq09mSqKwd6xj505uDhDlnZWd4AopOz0EoYjpuXgLb1MVg29nx+SahBaDyGZzMAeHk9cJNXiOsB9uTPAI9lrud8VxIAMxvj1R32/icmqUmg9WqtMollNyJINfra5nKj1WtIBdMelGOy1fulpASVnSBC/2LvHsn8oF/Wq6MhKXbVSJj77zBidGPOO302bxPP4N5+TNxPAiTJgmnJpJD5Nr8A+snSJlQwUyJtPVo6M7ded2Xk+oFiwSBU1hs=
before_install:
- npm install -g grunt-cli
script:
- npm test
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && grunt autoDeploy
